services:
  # Backend
  app:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  # mysql 
  mysql:
    image: mysql:8
    command: --local_infile=1 --secure-file-priv=''
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CSCI367   
      MYSQL_DATABASE: CSCI367MBTI 
    ports:
      - "3307:3306" 
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/Animes.csv:/docker-entrypoint-initdb.d/Animes.csv
      - ./mysql/Characters.csv:/docker-entrypoint-initdb.d/Characters.csv
      - ./mysql/Genres.csv:/docker-entrypoint-initdb.d/Genres.csv
      - mysql-data:/var/lib/mysql

  # Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"            
    depends_on:
      - app

volumes:
  mysql-data:
