# Build
FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY src/ ./src
WORKDIR /app/src
RUN CGO_ENABLED=0 GOOS=linux go build -o app main.go

# Binary
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/src/app .
EXPOSE 8080
CMD ["./app"]
