version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    command: --local_infile=1 --secure-file-priv=''
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 243629511   # 设置根密码
      MYSQL_DATABASE: rose_shop  
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./rose.csv:/docker-entrypoint-initdb.d/rose.csv
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
